### ISSUE TITLE
NgrokClientAutoConfigure使用默认配置报错（没有加其它配置）

### ISSUE THREAD

**Issue by ipqihujf** [cyejing/fast-ngrok#3]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [cn.cyejing.ngrok.autoconfigure.NgrokClientAutoConfigure]; nested exception is java.lang.ClassCastException: java.lang.UnsupportedClassVersionError cannot be cast to [Ljava.lang.Object;

**Comment by cyejing** [comment]
有没有更详细的错误信息，你的jdk版本是多少？貌似是class版本不兼容
